# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0209d2218745ba02a4ee910156e673f41d74bb35bbba4651ce871cd476f8abf996d49eb2c89c380cadeb9be9eeaa292e4dbf7d90713f1f98a035ac592a296ad7

test:
  secret_key_base: f9d063daae201d43508a94589bd4a298ed4126bd01fb47029edfc3ccb45db9401afb3e046d0b022ab6a9be2f4a279afc6d7cc3ad08b8ed46403428d35f27977c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
